name: PHPUnit

on:
  workflow_call:
    secrets:
      COMPOSER_AUTH:
        required: true

jobs:
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    env:
      # needed to install private packages from dmg-satis.net
      COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{secrets.COMPOSER_AUTH}}"} }' # [tl! **
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_USER: root
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: wordpress_test
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
    - uses: actions/checkout@v4
    # needed for some dependencies
    - name: Install Subverson
      run: sudo apt-get install -y subversion
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, soap, intl, gd, exif, iconv, imagick
        coverage: none
    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-interaction --optimize-autoloader
    - name: PHPUnit
      run: |
       composer run phpunit
