name: PHPUnit

on:
  workflow_call:
    secrets:
      COMPOSER_AUTH:
        required: true

jobs:
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    env:
      COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{secrets.COMPOSER_AUTH}}"} }'
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
          MYSQL_DATABASE: wordpress_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
    - uses: actions/checkout@v4
    - name: Install Subversion
      run: sudo apt-get install -y subversion &
    - name: Configure PHP
      uses: shivammathur/setup-php@v2
      with:
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, soap, intl, gd, exif, iconv, imagick, xdebug
        coverage: xdebug
    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-interaction --optimize-autoloader --ignore-platform-req=php
    - name: PHPUnit with Coverage
      run: |
        composer run phpunit
    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: tests/phpunit/coverage/
